LTO_ENABLE = yes
AUDIO_ENABLE = no
BLUETOOTH_ENABLE = no
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
DYNAMIC_TAPPING_TERM_ENABLE = no
EXTRAKEY_ENABLE = no
KEY_OVERRIDE_ENABLE = no
LEADER_ENABLE = no
MAGIC_ENABLE = no
MIDI_ENABLE = no
MOUSEKEY_ENABLE = no
RGBLIGHT_ENABLE = no
UNICODE_ENABLE = no

COMBO_ENABLE = yes
NKRO_ENABLE = yes
